### ISSUE TITLE
Sublime Text Auto-closing Tags

### ISSUE THREAD

**Issue by taylorzane** [vuejs/vue-syntax-highlight#67] opened 2016-09-13 16:24 UTC
When using Sublime Text (dev 3102) and the `vue-syntax-highlight` library, auto-closing a tag with string interpolation causes Sublime Text to use the wrong closing tag.

Example:

``` vue
<template>
  <div id="foo">{{ test }}
</template>
```

When adding `</` after `{{ test }}`, the following occurs.

``` vue
<template>
  <div id="foo">{{ test }}</{>
</template>
```

I would imagine this is a bug with ST3's auto-closing feature, but it's possible it's a bug with the syntax definition, so I'm posting this here.

**Comment by sewid** [comment] 2016-09-14 07:29
Same problem here - I can reproduce it.

**Comment by taylorzane** [comment] 2016-09-14 12:06
So I've determined that this issue is due to [Lines 317 & 319](https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L317,L319) in the language definition.

I'm assuming that ST is looking for the most recent `punctuation.definition.tag.*` and seeing the `{` as the previous one, even though it's not in the same scope.

If those lines are changed to something like `punctuation.definition.string.*` then the issue is resolved and the auto-closed tag is `</div>`.

@yyx990803 I wonder what the best name for this would be. 

The ST documentation seems to suggest any 'unspecific' scope should use `punctuation.definition.generic.*` 

I'll submit a PR with this change in a bit.

**Comment by taylorzane** [comment] 2016-09-14 14:40
This has been resolve in PR #69. The changes just need to be tagged in order to update Package Control.

**Comment by skyronic** [comment] 2018-05-09 22:30
Looks like the issue has been fixed, closing now.

**Closed by skyronic** 2018-05-09 22:30 UTC
