### ISSUE TITLE
Not highlighting CoffeeScript

### ISSUE THREAD

**Issue by azamat-sharapov** [vuejs/vue-syntax-highlight#4] opened 2015-07-23 17:42 UTC
See vuejs/Discussion#307 for description of issue.

I found out, that it's caused by [this change](https://github.com/vuejs/vue-syntax-highlight/commit/bc03d8417d5c3994c5d62fc1ba665062eae3aade#diff-e8e64165905d1aad3d27f8de0140b72aR1225). When reverting back this change (by manually editing that file), it works fine.

**Comment by taylorzane** [comment] 2015-07-23 23:16
:+1: Also experiencing this issue.

**Comment by yyx990803** [comment] 2015-07-24 01:45
Hmm, not sure why, but I'm also on Sublime 3 (build 3083) + BetterCoffeeScript, and it's highlighting it correctly for me =/

**Comment by taylorzane** [comment] 2015-07-24 02:07
So I did a couple things that made CoffeeScript syntax highlighting work...
(I am also using `ST3 build 3083` and `Better CoffeeScript`)

1. I used `PackageResourceViewer` to open the `Vue Syntax Highlighting` package
2. I modified the `vue.tmLanguage` file to read `text.html.basic` saved it.
3. (At this point the CoffeeScript highlights correctly)
4. I changed it back to `text.html.vue` and the code is still highlighting correctly
5. Restarted Sublime Text
6. Broken again.

Another approach I did was the following:

1. Uninstall `Better CoffeeScript`
2. Reinstall `Better CoffeeScript`
3. Still broken
4. Uninstall `Vue Syntax Highlighting`
5. Reinstall `Vue Syntax Highlighting`
6. Still broken

**Comment by azamat-sharapov** [comment] 2015-07-24 05:47
@taylorzane yeah i also used PackageResourceViewer to modify it. What OS are you using? I'm on Ubuntu 14.04 (64 bit).

@yyx990803 I looked at sublime docs, they say it should be `text.<lang_name>`, but I can't figure out where `lang_name` is coming from, couldn't find it in plugin files. Or is file extension just used as `lang_name` ?

**Comment by taylorzane** [comment] 2015-07-24 06:24
@azamat-sharapov I'm on Mac OS X 10.10.4 (Yosemite)

**Comment by yyx990803** [comment] 2015-07-25 03:38
Should be fixed now, this is actually caused by a problem with jade detection...(see #5)

**Closed by yyx990803** 2015-07-25 03:38 UTC

**Comment by azamat-sharapov** [comment] 2015-07-25 09:19
Thanks man
