### ISSUE TITLE
Sublime update broke vue-syntax-highlight

### ISSUE THREAD

**Issue by canyoudev** [vuejs/vue-syntax-highlight#138] opened 2018-05-07 11:40 UTC
Hello. Today's update broke `vue-syntax-highlight`. Any chance to fix it or provide solution?

**Comment by 747969780** [comment] 2018-05-07 11:42
me too

**Comment by canyoudev** [comment] 2018-05-07 11:46
I have 10 plugins, `vue-syntax-highlight` was the only one that have issues. I wish it was the only one working :smile:

**Comment by 747969780** [comment] 2018-05-07 11:54
2333,I wish so too

**Comment by tcamde** [comment] 2018-05-07 13:26
Broke for me too.
After reinstalling only have of the vue files seem to be recognized

**Comment by cjm0** [comment] 2018-05-07 13:34
need  source.less -> source.css.less

**Comment by kenmaclord** [comment] 2018-05-07 13:43
Same for me, but if you tag the vue single file as PHP  (view->syntax->php), it works as expected.

**Comment by skyronic** [comment] 2018-05-07 17:35
Lemme take a look today and see if I can find out what went wrong.

**Comment by skyronic** [comment] 2018-05-07 20:12
Hi All, can you tell me the following:

1. What file are you using? What are you seeing? Because quite a few issues seem to have cropped up and I want to find a clearer idea of what exactly you're seeing wrong.
2. Can you tell me the version of the package installed? Go to Cmd+Shift+P or Ctrl+Shift+P and select Installed Packages and find the syntax highlight.

![image](https://user-images.githubusercontent.com/80173/39722515-08dd293a-5211-11e8-9dcc-01619572e602.png)

I hope to get this fixed up this week, quite a few things have changed in Sublime, and we changed things to suit it.

In the meantime, you can try tagging the file as PHP as @kenmaclord suggests, but I'll try to find a better workaround in the meantime.

**Comment by alex-martinez** [comment] 2018-05-07 20:40
@skyronic

Version 3.2.6

What specifically happened to me is:

1. Upgraded Sublime to the newest version
2. Sublime notified me stating: `The following incompatible dependency was found installed: Vue Syntax Highlight`
3. Then all my opened *.vue file tabs switched automatically Plain Text

**My Solution**

I was able to switch the syntax back to "Vue Component" syntax without any issues.

**Comment by canyoudev** [comment] 2018-05-07 20:43
I have the same as @alex-martinez 

I also tried to reinstall plugin, as it asked me, but this didn't help.

**Comment by DanielCruz-fs** [comment] 2018-05-07 20:46
trying to fix it i messed up my settings...uhhhh has anyone solved it?? or should we wait for a new version coming soon..?

**Comment by canyoudev** [comment] 2018-05-07 20:56
Let's be patient :wink:  Sublime Text updates doesn't happens everyday, ha-ha. So it's already a happy day!

**Comment by skyronic** [comment] 2018-05-07 22:02
Ok can you try uninstalling the extension and installing it again? or running "Upgrade packages" from package control?

From what I can understand the issue is - we upgraded the extension a while ago but only supported sublime 3156+. Now your stable version of Sublime updated but still has an older version which is  marked as incompatible with newer versions of sublime.

Reinstalling _should_ hopefully fix it. Most things are working fine for me in Version 3170 (Sublime 3.1) but please do file issues for anything you encounter.

**Comment by canyoudev** [comment] 2018-05-07 22:48
I tried reinstall when I first encounter that issue, as I said earlier

> I also tried to reinstall plugin, as it asked me, but this didn't help.

**Comment by canyoudev** [comment] 2018-05-08 01:58
@skyronic also I have this error when I restar Sublime

```
Error loading syntax file "Packages/Vue Syntax Highlight/vue.tmLanguage": Unable to open Packages/Vue Syntax Highlight/vue.tmLanguage
```

**Comment by maxl960** [comment] 2018-05-08 03:02
ignored packages updated to: ["SublimeCodeIntel", "Vintage", "Vue Syntax Highlight"]
reloading settings Packages/User/Package Control.sublime-settings
warning: mnemonic t not found in menu caption Tools
reloading settings Packages/User/Preferences.sublime-settings
warning: mnemonic t not found in menu caption Tools
reloading settings Packages/User/Package Control.sublime-settings
warning: mnemonic t not found in menu caption Tools
ignored packages updated to: ["SublimeCodeIntel", "Vintage"]
generating syntax summary
warning: mnemonic t not found in menu caption Tools
Error loading scope:source.scheme: Unable to find syntax file for scope source.scheme in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.tsx: Unable to find syntax file for scope source.tsx in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.swift: Unable to find syntax file for scope source.swift in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.less: Unable to find syntax file for scope source.less in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.reason: Unable to find syntax file for scope source.reason in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.ts: Unable to find syntax file for scope source.ts in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.Kotlin: Unable to find syntax file for scope source.Kotlin in Packages/MarkdownEditing/Markdown.sublime-syntax
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
warning: mnemonic t not found in menu caption Tools
reloading settings Packages/User/Preferences.sublime-settings
warning: mnemonic t not found in menu caption Tools

**Comment by maxl960** [comment] 2018-05-08 03:14
The problem has been solved。
![image](https://user-images.githubusercontent.com/8602874/39736066-fe5f86ec-52b0-11e8-8d80-aa1308ab55da.png)

**Comment by DanielCruz-fs** [comment] 2018-05-08 03:47
![screenshot_1](https://user-images.githubusercontent.com/29930991/39736984-c4084728-5250-11e8-99df-bfa2d2abd11a.png)

I am not able to fix this... any advice???
i do not wanna migrate to vscode xd

**Comment by 747969780** [comment] 2018-05-08 03:52
It seems that only the less syntax cannot be highlighted
![image](https://user-images.githubusercontent.com/29268460/39737135-2c8878e4-52b6-11e8-9899-8f6ae3ce01f4.png)

**Comment by skyronic** [comment] 2018-05-08 04:05
@DanielCruz-fs  workaround for now: Install babel package, disable the JavaScript package

@747969780 I've got a PR #139 which I'll merge in and make a release soon.

**Comment by DanielCruz-fs** [comment] 2018-05-08 04:13
https://download.sublimetext.com/Sublime%20Text%20Build%203143%20x64%20Setup.exe


there!!!!! I went back to 3143
And solved my highlight issue of vuejs

**Comment by canyoudev** [comment] 2018-05-08 11:43
What are you talking about? How problem could be solved if nothings happened? Still no highlight when I open Vue files. I had to do it manually, which is retarded.

**Comment by canyoudev** [comment] 2018-05-08 11:44
And each time I open Sublime I got `Error loading syntax file "Packages/Vue Syntax Highlight/vue.tmLanguage": Unable to open Packages/Vue Syntax Highlight/vue.tmLanguage`

Problem is solved, right.

**Comment by Thom1729** [comment] 2018-05-08 20:00
`Error loading syntax file "Packages/Vue Syntax Highlight/vue.tmLanguage": Unable to open Packages/Vue Syntax Highlight/vue.tmLanguage`

Between the 3.0 and 3.1 release, the Vue syntax was rewritten. Your open files are trying to use the old version of the syntax, which isn't there anymore. If you close and reopen the files, they will find the new syntax. You can also manually select the Vue Component syntax to get rid of the error. Restarting Sublime will not help, because it will save the view settings across the restart.

**Comment by awardx** [comment] 2018-05-08 22:04
Resolved! I uninstalled all Vue packages from my Sublime and reinstalled only Vue Syntax Highlight

To remove package from Sublime: ctrl+shift+p then type Package Control: remove package

**Comment by canyoudev** [comment] 2018-05-09 10:03
Absolute lie. NOTHING IS RESOLVED.

**Comment by awardx** [comment] 2018-05-09 10:12
Well, this worked for me and still works. I found that the issue was that I had three Vue syntax options in the view->syntax list, so I deleted every single Vue related package to remove all of them and then I reinstalled just Vue Syntax Highlight. Now I don't have any problems anymore. I have Sublime build 3170 and Vue Syntax Highlight v3.2.6

**Comment by alex-martinez** [comment] 2018-05-09 15:45
@canyoudev I know you've already done it, but can you try uninstalling and reinstalling Vue Syntax Highlight? Once it's reinstalled, make sure your .vue file's syntax is set to Vue Component.

**Comment by justanotherco** [comment] 2018-05-09 17:16
Can also confirm - uninstalling, closing sublime and then re-installing fixed it. Thanks guys!

**Comment by jbruni** [comment] 2018-05-09 17:17
Oh... this issue made me realize I have (and regularly use) Sublime Text at four different environments: two Linux VMs I use for development, plus the corresponding two hosts (Windows 10 and MacOS High Sierra).

In all these, Sublime Text uninstalled Vue Syntax Highlight after the upgrade, claiming some "sync" issue, and requesting to uninstall and reinstall the package.

**Comment by slorenzo** [comment] 2018-05-11 17:28
+1

**Comment by Thom1729** [comment] 2018-05-11 17:40
I think I've lost track of what the issue is.

To anyone who still has an issue:

- Have you tried un/reinstalling the package?
- Have you tried closing and reopening all Vue files?
- What is the problem, currently?

I suspect that all of the open problems are hiccups with the upgrade process that can be solved by a bit of user intervention, and that can *only* be solved by a bit of user intervention.

**Comment by prowseed** [comment] 2018-05-11 18:59
Less syntax highlighting in single *.vue component does not work for me, although scss works. I do have tried reinstalling the package, restarting sublime many times, removed files manually etc.

**Comment by skyronic** [comment] 2018-05-11 19:42
@prowseed this has been fixed and a new version will be released soon with less highlighting fixed.

**Comment by skyronic** [comment] 2018-05-11 21:44
Ok. v3.3.0 has been released and  is live on Sublime's package control.

![image](https://user-images.githubusercontent.com/80173/39948112-80add854-5542-11e8-84bb-8b6c251707eb.png)

This has been tested quite thoroughly and should fix most issues you're encountering.

Troubleshooting steps if it doesn't work for you right away:

1. Delete extension using "Remove Package" from package control, and reinstall.
2. If that doesn't work, check that your packages directory isn't synced on dropbox, git, etc.

### Reporting issue

I will close this issue. If you encounter issues, please open a new issue, with the following:

1. Which OS, version of sublime, etc
2. Screenshot of sublime, if applicable.
3. Some description of how we can reproduce the error.

**Closed by skyronic** 2018-05-11 21:44 UTC

**Comment by ielgnaw** [comment] 2018-08-09 01:41
create a new file, the same content with xx file, put it into the vue-syntax-highlight directory...

**Comment by JDsWebService** [comment] 2018-10-14 03:12
Can confirm that this new version of the package does indeed work. Just to be on the safe side, I included 'text/javascript' in the script tag and 'text/css' in the style tag.

![screenshot]

[screenshot]: https://i.imgur.com/fvO6G2Q.png
