### ISSUE TITLE
Linter is not being triggered on vue files

### ISSUE THREAD

**Issue by ellipticaldoor** [vuejs/vue-syntax-highlight#132] opened 2018-03-04 16:19 UTC
So I install sublimelinter, sublimelinter-eslint and vue syntax highlight but it looks like the linter is working on .js files but not on .vue

There is something special that I have to do to trigger the lint on .vue files?

**Comment by nervouself** [comment] 2018-03-05 10:11
I've been in the same situation.

SublimeLinter version v4.0.2, just updated.

**Comment by nervouself** [comment] 2018-03-06 03:18
it's fixed by SublimeLinter-eslint.

**Comment by nervouself** [comment] 2018-03-06 03:18
It's fixed by SublimeLinter-eslint.

**Comment by skyronic** [comment] 2018-05-09 21:41
I'm not sure if this is an issue. I'm closing this since there doesn't seem to be an issue with the syntax highlight in itself. Please feel free to reopen if there's anything caused by this extension.

**Closed by skyronic** 2018-05-09 21:41 UTC
