### ISSUE TITLE
Issues in Sublime 3103

### ISSUE THREAD

**Issue by w0bbes** [vuejs/vue-syntax-highlight#36] opened 2016-02-09 10:52 UTC
My new Sublime build wrecks the highlighting... 

Anyone else with these issues?

**Comment by akralj** [comment] 2016-02-14 16:17
yes.

**Comment by yyx990803** [comment] 2016-02-14 17:47
Hmm it's working fine for me. Are you on Windows?

**Comment by w0bbes** [comment] 2016-02-15 09:59
Yes I am. The highlighting is weird.. At least diff then it was.
![vue-hightlighting](https://cloud.githubusercontent.com/assets/4660590/13045371/35d151e6-d3d3-11e5-8b9a-6e4320d2e937.jpg)

**Comment by w0bbes** [comment] 2016-02-15 10:00
HTML and SASS is fine btw.

**Comment by NemoAlex** [comment] 2016-02-16 08:10
![image](https://cloud.githubusercontent.com/assets/1411460/13070474/bce79fa6-d4c7-11e5-8a94-e607cd000dee.png)

Also, JADE stop working.
Sublime Text 3103 on OS X 10.11.3

**Comment by danneker** [comment] 2016-02-16 21:44
JADE syntax is not working for me either.
Sublime Text 3103 on Ubuntu 15.04

**Comment by azamat-sharapov** [comment] 2016-02-17 06:19
Did you guys check if raw `.jade` files highlighted fine?

**Comment by NemoAlex** [comment] 2016-02-17 06:31
@azamat-sharapov Of course `.jade` works fine.

**Comment by danneker** [comment] 2016-02-17 10:03
Yes that was the first thing I checked. If I copy the same code to a .jade file the syntax highlighting works as expected.

**Comment by Gomah** [comment] 2016-02-22 00:16
I had the same problem, it's probably due to Vuejs Complete Package & vue-syntax-highlight packages combination:
![screen shot 2016-02-22 at 11 08 28 am](https://cloud.githubusercontent.com/assets/2362138/13206576/2e28983c-d955-11e5-9fb1-39f68933f97d.png)

Even by selecting the other "Vue component" option, I couldn't make it works so I fixed it by removing the Vuejs Complete Package.

**Comment by danneker** [comment] 2016-03-01 10:36
I removed the 'Vuejs Complete Package' and the the syntax highlighting for jade works fine for me too.

**Comment by yyx990803** [comment] 2016-03-06 00:57
It seems this is caused by the Vue Complete Package - closing for now.

**Closed by yyx990803** 2016-03-06 00:57 UTC

**Comment by ericwangqing** [comment] 2017-05-25 02:31
Actually it doesn't work even without Vue Complete Package installed. 
![image](https://cloud.githubusercontent.com/assets/364773/26433415/392a9020-4135-11e7-9345-29994a9d2736.png)
